- hosts: windows
  vars:
  
  tasks:
  
- name: Stop service
  win_service:
    name: {{ srv_name }}
    state: stopped
  register: service_output
  
- name: Kill process
  when: service_output.state != 'stopped'
  win_command: taskkill /f /fi "Services eq {{ srv_name }}"
  register: cmd_result_service_kill 
  
- name: Delete service
  win_service:
    name: {{ srv_name }}
    state: absent
  
- name: Clean base directory
  # Get child-folders, exclude logs, delete all files
  
- name: Deploy packets
- name: Deploy config

- name: Create service
  win_service:
    name: {{ srv_name }}
    path: {{ srv_path }}
    display_name: {{ srv_display_name }}
    username: DOMAIN\User  {{ srv_username }}
    password: {{ srv_password }}
    dependencies: {{ srv_dependencies }}
    description: {{ srv_description }}

- name: Setup permissions
  win_acl:
    path: {{ srv_directory }}
    user: {{ srv_username }}
    rights: FullControl, Modify, Read
    type: allow
    state: present
    inherit: ContainerInherit, ObjectInherit

- name: Start service
  win_service:
    name: {{ srv_name }}
    state: started
  register: service_output

- name: Remove temp directory
  win_file:
    path: {{ temp_directory }}
    state: absent

- name: Send mail notification
