tasks:
 
- name: Install runtimes
  yum:
    name: 
      - epel-release
      - nuget
      - aspnetcore-runtime-3.1
      - dotnet-runtime-3.1
      - dotnet-sdk-3.1
    state: present
     
 - name: Add new source for nuget
   command: nuget sources Add -Name "MyServer" -Source \\myserver\packages
   
 - name: Install package
   command: nuget install Packname -OutputDirectory packages
   
 - name: run app
   command: mono-service {{ svc_name }}
