tasks:

- name: Add repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    
- name: Install app dependencies
  yum:
    name:
    - perl 
    - perl-devel 
    - perl-ExtUtils-Embed 
    - libxslt 
    - libxslt-devel 
    - libxml2 
    - libxml2-devel 
    - gd 
    - gd-devel 
    - GeoIP 
    - GeoIP-devel
    state: present

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
    
- name: Create app directory
  file:
    path: "{{ app_path }}"
    state: directory
    mode: '0755'
    
- name: Download apps rpm
  get_url:
    url: "{{ app_pack_url }}"
    dest: "{{ app_path }}"
