tasks:

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
    
- name: Install app dependencies
  yum:
    name:
    - epel-release
    - perl 
    - perl-devel 
    - perl-ExtUtils-Embed 
    - libxslt 
    - libxslt-devel 
    - libxml2 
    - libxml2-devel 
    - gd 
    - gd-devel 
    - GeoIP 
    - GeoIP-devel
    state: latest
    
- name: Add service user
  user:
    name: "{{ svc_user }}"

- name: Create service directory
  file:
    path: "{{ svc_path }}"
    state: directory
    mode: '0755'

- name: Download nuget packet
  get_url:
    url: "{{ nuget_url }}"
    dest: "{{ svc_path }}/{{ zip_name }}"
    
- name: Unarchive nuget packet
  unarchive:
    src: "{{ svc_path }}/{{ zip_name }}"
    dest: "{{ svc_path }}"
     
- name: Create systemd unit
  copy:
    dest: "/etc/systemd/system/{{svc_name}}"
    content: |
    [Unit]
    Description={{ svc_description }}
    Documentation={{ svc_documentation }}
    After=network-online.target remote-fs.target nss-lookup.target
    Wants=network-online.target

    [Service]
    Type=forking
    PIDFile={{ svc_path }}/{{ svc_pid }}
    ExecStartPre={{ svc_path }}/{{ svc_runner }} -t -c {{ svc_conf }}
    ExecStart={{ svc_path }}/{{ svc_runner }} -c {{ svc_conf }}
    ExecReload=/bin/kill -s HUP $MAINPID
    ExecStop=/bin/kill -s TERM $MAINPID

    [Install]
    WantedBy=multi-user.target

- name: Just force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: Start and enable service
  systemd:
    name: {{ svc_name }}
    state: started
    enabled: yes
