tasks:

- name: Include centos specific vars
  include_vars:
    file: win-spec.yml

- name: Check if a service is installed
  win_service:
    name: "{{ svc_name }}"
  register: service_check
  
- include_tasks: winprep.yml
  when: service_check.exists == False
  
- include_tasks: winsvcprep.yml
  when: service_check.exists == True
  
- name: Download nuget apppack
  win_get_url:
    url: "{{ app_pack_url }}"
    dest: "{{ svc_path }}\\{{ apppack_name }}"

- name: Unzip nuget apppack
  win_unzip:
    src: "{{ svc_path }}\\{{ apppack_name }}"
    dest: "{{ svc_path }}"
    
- name: Setup permissions
  win_acl:
    path: "{{ svc_path }}\\logs"
    user: "{{ svc_username }}"
    rights: FullControl, Modify, Read
    type: allow
    state: present
    inherit: ContainerInherit, ObjectInherit

- name: Create config directories
  win_file:
    path: "{{ item.path }}"
    state: directory
  loop: "{{ template_conf_dirs }}"

- name: Create files from Jinja2 templates
  win_template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
  loop: "{{ template_paths }}"

- name: Create service
  win_service:
    name: "{{ svc_name }}"
    path: "{{ svc_path }}\\nginx.srv.exe"
    display_name: "{{ svc_display_name }}"
    username: "{{ svc_username }}"
    password: "{{ svc_password }}"
    dependencies: "{{ svc_dependencies }}"
    dependency_action: add
    description: "{{ svc_description }}"

- name: Start service
  win_service:
    name: "{{ svc_name }}"
    state: started
  register: service_output

#???
- name: Remove temp dir
  win_file:
    path: "{{ temp_dir }}"
    state: absent

- name: Send mail notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: username@gmail.com
    password: mysecret
    to: John Smith <john.smith@example.com>
    subject: Ansible-report
    body: System "{{ ansible_hostname }}" has been successfully provisioned.
  delegate_to: localhost
