tasks:

yum install -y yum-utils \
  device-mapper-persistent-data \
  lvm2
  
  yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo
    
    yum install docker-ce docker-ce-cli containerd.io
    
    systemctl start docker
    enable
    
- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
  
- name: Install docker dependencies
  yum:
    name:
    - epel-release
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    
- name: Add repository
  yum_repository:
    name: docker
    description: yum docker ce repo
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo
    
- name: Install app dependencies
  yum:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    
- name: Allow docker ports
   firewalld:
     port: {{ item }}
     permanent: yes
     state: enabled
   loop:
   - 2375/tcp
   - 2376/tcp
   - 7946/tcp
   - 7946/udp
    
    
