tasks:
  
- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
  
- name: Install docker dependencies
  yum:
    name:
    - epel-release
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    state: present
    
- name: Add repository
  yum_repository:
    name: docker
    description: yum docker ce repo
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo
    
- name: Install app dependencies
  yum:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: present
    
- name: Allow docker ports
   firewalld:
     port: {{ item }}
     permanent: yes
     state: enabled
   loop:
   - 2375/tcp
   - 2376/tcp
   - 7946/tcp
   - 7946/udp
   - 4789/udp

- name: Start and enable service
  systemd:
    name: docker
    state: started
    enabled: yes
